### ISSUE TITLE
Código de conduta e licença do repositorio.

### ISSUE THREAD

**Issue by LamequeFernandes** [deeplearningunb/FacEmotions#1]
## Descrição da Issue
Melhorando os repositorio.

## Tasks:
- [x] Adição no Código de Conduta
- [x] Adição da Licensa do repositorio.

## Critérios de Aceitação:
- [x] Todos os membros concordarem.
